In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\Muthulingam\OneDrive\Documents\23082025\employee_salaries_large.csv')

In [4]:
df.head(10)

   EmployeeID Department Designation  Experience CollegeTier   Salary
0           1         IT        Lead           6      Tier 1  1310795
1           2    Finance  Senior Dev          14      Tier 2  1608343
2           3    Support     Manager           6      Tier 2  1362265
3           4         IT        Lead          18      Tier 1  2232194
4           5    Finance    Director          10      Tier 2  1997191
5           6         IT   Associate           3      Tier 2   624023
6           7         IT  Senior Dev           2      Tier 3   691685
7           8  Marketing     Analyst           1      Tier 2   425735
8           9    Finance  Senior Dev          11      Tier 2  1412101
9          10      Sales      Intern           1      Tier 2   261311

In [5]:
df.tail(10)

      EmployeeID Department Designation  Experience CollegeTier   Salary
5017         897  Marketing   Associate           2      Tier 2   594048
5018         898         IT      Intern          11      Tier 2   944087
5019         899         HR      Intern          14      Tier 3  1026335
5020         900      Sales   Associate           4      Tier 1   798602
5021         901  Marketing     Analyst          19      Tier 1  1818901
5022         902  Marketing   Associate          18      Tier 2  1630196
5023         903  Marketing     Manager           2      Tier 2  1097626
5024         904    Finance      Intern           0      Tier 2   202857
5025         905    Finance  Senior Dev           5      Tier 2   979982
5026         906    Finance   Associate           1      Tier 3   431980

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5027 entries, 0 to 5026
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   5027 non-null   int64
 1   Department   5027 non-null   object
 2   Designation  5015 non-null   object
 3   Experience   5027 non-null   int64
 4   CollegeTier  5027 non-null   object
 5   Salary       5027 non-null   int64
dtypes: int64(3), object(3)
memory usage: 235.8+ KB

In [7]:
df=df.dropna()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5015 entries, 0 to 5026
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmployeeID   5015 non-null   int64
 1   Department   5015 non-null   object
 2   Designation  5015 non-null   object
 3   Experience   5015 non-null   int64
 4   CollegeTier  5015 non-null   object
 5   Salary       5015 non-null   int64
dtypes: int64(3), object(3)
memory usage: 274.3+ KB

In [19]:
df.groupby('Designation')['Salary'].sum()

Designation
Analyst        671862987
Associate      792958088
Director      1322391995
Intern         583070682
Lead          1032909973
Manager       1158327013
Senior Dev    1021173832
Name: Salary, dtype: int64

In [21]:
df['Salary'].describe().round()

count       4988.0
mean     1319706.0
std       543065.0
min       182336.0
25%       924151.0
50%      1301442.0
75%      1687877.0
max      2949098.0
Name: Salary, dtype: float64

In [9]:
df =df[['Department','Designation','Experience','CollegeTier','Salary']]

In [10]:
df

     Department Designation  Experience CollegeTier   Salary
0            IT        Lead           6      Tier 1  1310795
1       Finance  Senior Dev          14      Tier 2  1608343
2       Support     Manager           6      Tier 2  1362265
3            IT        Lead          18      Tier 1  2232194
4       Finance    Director          10      Tier 2  1997191
...         ...         ...         ...         ...      ...
5022  Marketing   Associate          18      Tier 2  1630196
5023  Marketing     Manager           2      Tier 2  1097626
5024    Finance      Intern           0      Tier 2   202857
5025    Finance  Senior Dev           5      Tier 2   979982
5026    Finance   Associate           1      Tier 3   431980

[5015 rows x 5 columns]

In [11]:
df.duplicated().sum()

np.int64(27)

In [12]:
df =df.drop_duplicates()

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
(df['Salary']).min()

np.int64(182336)

In [17]:
df['Designation'].unique()

array(['Lead', 'Senior Dev', 'Manager', 'Director', 'Associate',
       'Analyst', 'Intern'], dtype=object)

In [18]:
df['CollegeTier'].unique()

array(['Tier 1', 'Tier 2', 'Tier 3'], dtype=object)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4988 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Department   4988 non-null   object
 1   Designation  4988 non-null   object
 2   Experience   4988 non-null   int64
 3   CollegeTier  4988 non-null   object
 4   Salary       4988 non-null   int64
dtypes: int64(2), object(3)
memory usage: 233.8+ KB

In [19]:
df.to_csv('Cleaned_Employees_salaries_Data.csv', index=False)