In [11]:
import pandas as pd

df=pd.read_csv(r'C:\Users\Muthulingam\OneDrive\Documents\23082025\Cleaned_Employees_salaries_Data.csv')

In [12]:
df

     Department Designation  Experience CollegeTier   Salary
0            IT        Lead           6      Tier 1  1310795
1       Finance  Senior Dev          14      Tier 2  1608343
2       Support     Manager           6      Tier 2  1362265
3            IT        Lead          18      Tier 1  2232194
4       Finance    Director          10      Tier 2  1997191
...         ...         ...         ...         ...      ...
4983         HR     Analyst          13      Tier 2  1176595
4984    Support        Lead           3      Tier 2   984926
4985         HR  Senior Dev           7      Tier 1  1279457
4986    Finance      Intern           3      Tier 3   357727
4987  Marketing        Lead           3      Tier 1  1123693

[4988 rows x 5 columns]

In [13]:
df['CollegeTier'].unique()

array(['Tier 1', 'Tier 2', 'Tier 3'], dtype=object)

In [14]:
'''1.Text -->Numeric
2.Column transformation
3.pipline 
4.line regression (Model) -algorithm 
5.error -->avoid'''

'1.Text -->Numeric\n2.Column transformation\n3.pipline \n4.line regression (Model) -algorithm \n5.error -->avoid'

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [16]:
X =df[['Department','Designation','Experience','CollegeTier']]
y =df['Salary']

In [17]:
X

     Department Designation  Experience CollegeTier
0            IT        Lead           6      Tier 1
1       Finance  Senior Dev          14      Tier 2
2       Support     Manager           6      Tier 2
3            IT        Lead          18      Tier 1
4       Finance    Director          10      Tier 2
...         ...         ...         ...         ...
4983         HR     Analyst          13      Tier 2
4984    Support        Lead           3      Tier 2
4985         HR  Senior Dev           7      Tier 1
4986    Finance      Intern           3      Tier 3
4987  Marketing        Lead           3      Tier 1

[4988 rows x 4 columns]

In [18]:
y

0       1310795
1       1608343
2       1362265
3       2232194
4       1997191
         ...
4983    1176595
4984     984926
4985    1279457
4986     357727
4987    1123693
Name: Salary, Length: 4988, dtype: int64

In [19]:
preprocessor =ColumnTransformer(

                  transformers =
                                 [
                                   ('Cat',OneHotEncoder(drop='first'),['Department','Designation','CollegeTier']),
                                   ('num','passthrough',['Experience'])
                                 ]
)

In [20]:
model =Pipeline(
         steps = 
               [
                 ('preprocessor', preprocessor),
                 ('regressor',LinearRegression())

               ]
)

In [21]:
X_train, X_test , y_train, y_test =train_test_split(X,y,test_size =.2, random_state=42)
model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('Cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['Department', 'Designation',
                                                   'CollegeTier']),
                                                 ('num', 'passthrough',
                                                  ['Experience'])])),
                ('regressor', LinearRegression())])

In [22]:
y_pred = model.predict(X_test)
mse =mean_squared_error(y_test,y_pred)

In [24]:
df

     Department Designation  Experience CollegeTier   Salary
0            IT        Lead           6      Tier 1  1310795
1       Finance  Senior Dev          14      Tier 2  1608343
2       Support     Manager           6      Tier 2  1362265
3            IT        Lead          18      Tier 1  2232194
4       Finance    Director          10      Tier 2  1997191
...         ...         ...         ...         ...      ...
4983         HR     Analyst          13      Tier 2  1176595
4984    Support        Lead           3      Tier 2   984926
4985         HR  Senior Dev           7      Tier 1  1279457
4986    Finance      Intern           3      Tier 3   357727
4987  Marketing        Lead           3      Tier 1  1123693

[4988 rows x 5 columns]

In [25]:
new_employee =pd.DataFrame (

                            [
                            {'Department' : 'IT' ,
                              'Designation':  'Lead',
                               'Experience' : 6 ,
                               'CollegeTier' : 'Tier 1'
                            } 

                            ]
)

In [26]:
model.predict(new_employee)

array([1338899.29001028])

In [27]:
import joblib

joblib.dump(model, 'Salary_Prediction.pkl')

['Salary_Prediction.pkl']